appMode: Production
appScope: prod
app:
  replicaCount: 3
  minReplicaCount: 2
  maxReplicaCount: 5
  defaultDomain: be.exceptionless.io
  domains:
    - be.exceptionless.io
    - app.exceptionless.io
    - app.exceptionless.com
api:
  replicaCount: 5
  minReplicaCount: 2
  maxReplicaCount: 5
  defaultDomain: collector.exceptionless.io
  domains:
    - collector.exceptionless.io
    - collector.exceptionless.com
    - api.exceptionless.io
    - api.exceptionless.com
    - config.exceptionless.io
    - heartbeat.exceptionless.io
jobs:
  eventNotifications:
    replicaCount: 2
  eventPosts:
    replicaCount: 2
    minReplicaCount: 2
    maxReplicaCount: 10
  eventUserDescriptions:
    replicaCount: 2
  mailMessage:
    replicaCount: 2
  webhooks:
    replicaCount: 2
  workitem:
    replicaCount: 4
    minReplicaCount: 2
    maxReplicaCount: 5

config:
  EX_EnableSnapshotJobs: "true"
  EX_SmtpFrom: "Exceptionless <noreply@exceptionless.io>"
  EX_TestEmailAddress: "test@exceptionless.io"
  EX_EnableArchive: "false"
  EX_Serilog__MinimumLevel__Default: "Warning"
  EX_Apm__EnableLogs: "true"
  EX_Apm__FullDetails: "true"
  EX_OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  EX_OTEL_TRACES_SAMPLER_ARG: "0.1"
  EX_OTEL_LOG_LEVEL: "warn"
